### ISSUE TITLE
about the product view in second site

### ISSUE THREAD

**Issue by mj-kiwi** [axis/axiscommerce#14] opened 2010-10-24 05:55 UTC
the product page can't show correctly.
the page will redirect to category view.

my step:
1,create new site named "new site"
2,create new category named"test category" under root category of the new site
3,copy some "electronic" product from main site to new site
4,in the front end, I want to access the product detail page, but the page will be redirected to category.

how can I fixed this issue?

**Comment by 0m3r** [comment] 2010-10-27 14:12
Thank you for you cooperation I was able to reproduce this bug. This problem  is caused by error in products copy feature  that is outdated right now. Problem can be solved by updating data in the  table "catalog_hurl". This issue will be fixed in next hotfix

**Comment by 0m3r** [comment] 2010-10-28 08:49
hotfix http://github.com/axis/axiscommerce/commit/db8329e97efd783ea75961e3d8c7b4a37b09292c

**Closed as completed by 0m3r** 2010-10-28 08:49 UTC
Labels: bug
